sudo: false
language: perl
perl:
    - "5.20-shrplib"
    - "5.18-shrplib"
    - "system-perl"
env:
    - CC=clang
    - CC=gcc

addons:
    apt:
        packages:
            - libperl-dev
            - elinks

before_install:
    - perl -V

install: true

script:
    - ./autogen.sh --with-proxy --with-bot --with-perl=module --prefix=$HOME/irssi-build
    - cat config.log
    - make CFLAGS="-Wall -Werror"
    - make install
